apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-app
        image: 590184096928.dkr.ecr.ap-south-1.amazonaws.com/my-image-repo:latest
        ports:
        - containerPort: 8082
        resources:  
          limits:
            cpu: "1" 
            memory: "2Gi"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/db # Mount path inside the container
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-app-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
    #nodePort: 30036
  selector:
    app: laravel-app