version: "3.9"

services:
  web:
    build: .
    ports:
      - "8082:80"
    environment:
      - APP_ENV=local
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/conduit.sqlite
    volumes:
      - .:/var/www/html
      - C:\Users\user\Desktop\sqlitedb:/var/www/html
