apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-sqlite-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0542868b2cdd1451a 

