apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-sqlite-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2  # Specify the StorageClass name
  awsElasticBlockStore:
    volumeID: vol-0542868b2cdd1451a  # Ensure this is correct for AWS EBS
