apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-new
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-0542868b2cdd1451a  # Replace with your EBS volume ID
    fsType: ext4  # or your desired filesystem type
