apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-ebs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: aws-ebs
  hostPath:
    # Replace with your actual EBS volume details
    path: /dev/xvda  # Adjust device path based on your EBS volume
  awsElasticBlockStore:
    volumeID: vol-0542868b2cdd1451a  # Replace with your EBS volume ID
    fsType: gp3  # Specify filesystem type

