apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-ebs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: aws-ebs  # Optional: Reference a storage class
  awsElasticBlockStore:
    volumeID: vol-079b35b1f834afe26  # Replace with your EBS volume ID
    fsType: ext4  # Specify filesystem type

