apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: my-new-container
      image: nginx
      volumeMounts:
        - name: my-ebs-volume
          mountPath: /data
  resources:
  limits:
    memory: "512Mi"  # Example memory limit
    cpu: "0.5"       # Example CPU limit
  requests:
    memory: "256Mi"  # Example memory request
    cpu: "0.2"
  volumes:
    - name: my-ebs-volume
      persistentVolumeClaim:
        claimName: my-ebs-pvc
