apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: my-new-container
      image: nginx
      resources:
        limits:
          memory: "4Gi"  # Example memory limit
          cpu: "2"       # Example CPU limit
        requests:
          memory: "1Gi"  # Example memory request
          cpu: "2"
      volumeMounts:
        - name: db-persistent-storage
          mountPath: /data
  volumes:
    - name: db-persistent-storage
      persistentVolumeClaim:
        claimName: my-ebs-pvc
